[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surrealdb = { version = "1.0.0-beta.11", features = ["kv-speedb"] }
axum = { workspace=true }
tokio = { workspace=true }
thiserror = { workspace=true }
anyhow = { workspace=true }
serde = { workspace=true }
serde_json = { workspace=true }
envy = "0.4"
serde_with = { version = "3" }
chrono = { version = "0.4" }
hmac = "0.12"
sha2 = "0.10"
hex = { version = "0.4" }
lazy_static = { version = "1" }